# Generated by Django 4.2.6 on 2023-10-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
