# Generated by Django 4.2.6 on 2023-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_concurrentexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentexpense',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
